server:
  port: 1200
contacts :
  message : "student contact information"
  details :
    name : "java techocrat"  
    address : "A/54 saheed Nagar,Odisha"
  contactNumber :
    -  +91 9437010139
    -  +91 7978895150
    -  +91 6372152110
